In [ ]:
# numpy - numerical python
# pandas - panel data analysis
# matplotlib
# searborn
# sklearn - scikit learn
# scipy - scientific python
# statsmodels

# Installation of packages
# pip install PACKAGE_NAME==VERSION - install the package
# !pip install PACKAGE_NAME - Jupyter notebook, VSCode

import numpy as np # np is alias
import matplotlib.pyplot as plt # from matplotlib import pyplot as plt

In [3]:
np.__version__

'2.1.3'

In [4]:
dir(np)

['False_',
 'ScalarType',
 'True_',
 '_CopyMode',
 '_NoValue',
 '__NUMPY_SETUP__',
 '__all__',
 '__array_api_version__',
 '__array_namespace_info__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__expired_attributes__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__numpy_submodules__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_array_api_info',
 '_core',
 '_distributor_init',
 '_expired_attrs_2_0',
 '_get_promotion_state',
 '_globals',
 '_int_extended_msg',
 '_mat',
 '_msg',
 '_no_nep50_warning',
 '_pyinstaller_hooks_dir',
 '_pytesttester',
 '_set_promotion_state',
 '_specific_msg',
 '_type_info',
 '_typing',
 '_utils',
 'abs',
 'absolute',
 'acos',
 'acosh',
 'add',
 'all',
 'allclose',
 'amax',
 'amin',
 'angle',
 'any',
 'append',
 'apply_along_axis',
 'apply_over_axes',
 'arange',
 'arccos',
 'arccosh',
 'arcsin',
 'arcsinh',
 'arctan',
 'arctan2',
 'arctanh',
 'argmax',
 'argmi

In [ ]:
# numpy - np.ndarray

# Properties -
# 1. nD
# 2. Homogeneous
# 3. Broadcasting is allowed
# 4. Vectorization is allowed

# Ways to create numpy arrays:
# 1. Casting the raw python data structure: list
# 2. By default np function: np.zeros, np.ones, np.zeros_like, np.ones_like, np.full, np.linspace, np.arange, np.linspace, np.random.randint...

# Different versions of table:
# 1. Wide table, - headers are in rows 2. long table (most common) - headers are in columns, 3. Cross table - headers will be part of both rows and columns

a1 = np.array([1,2,3,5,4,7,6], dtype=np.int16)

a1.dtype # Defines the type of data

dtype('int16')

In [ ]:
a1.nbytes # Defines the space it's taking in my system

14

In [ ]:
a1.size # Defines the number of elements

7

In [ ]:
a1.shape # The shape of array

(7,)

In [ ]:
a1.ndim # Dimension of array

1

In [ ]:
np.zeros((2,2), dtype=np.int8) # Total 4 values with 2 rows and 2 columns

array([[0, 0],
       [0, 0]], dtype=int8)

In [21]:
np.ones((2,3), dtype=np.int16)

array([[1, 1, 1],
       [1, 1, 1]], dtype=int16)

In [22]:
np.full((3,3), fill_value='abc')

array([['abc', 'abc', 'abc'],
       ['abc', 'abc', 'abc'],
       ['abc', 'abc', 'abc']], dtype='<U3')

In [24]:
np.ones_like(a1)

array([1, 1, 1, 1, 1, 1, 1], dtype=int16)

In [26]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.arange(1,100,0.5) # Helpful in defining fractional range - useful when we know the exact breakdown

array([ 1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,
        6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5, 11. , 11.5,
       12. , 12.5, 13. , 13.5, 14. , 14.5, 15. , 15.5, 16. , 16.5, 17. ,
       17.5, 18. , 18.5, 19. , 19.5, 20. , 20.5, 21. , 21.5, 22. , 22.5,
       23. , 23.5, 24. , 24.5, 25. , 25.5, 26. , 26.5, 27. , 27.5, 28. ,
       28.5, 29. , 29.5, 30. , 30.5, 31. , 31.5, 32. , 32.5, 33. , 33.5,
       34. , 34.5, 35. , 35.5, 36. , 36.5, 37. , 37.5, 38. , 38.5, 39. ,
       39.5, 40. , 40.5, 41. , 41.5, 42. , 42.5, 43. , 43.5, 44. , 44.5,
       45. , 45.5, 46. , 46.5, 47. , 47.5, 48. , 48.5, 49. , 49.5, 50. ,
       50.5, 51. , 51.5, 52. , 52.5, 53. , 53.5, 54. , 54.5, 55. , 55.5,
       56. , 56.5, 57. , 57.5, 58. , 58.5, 59. , 59.5, 60. , 60.5, 61. ,
       61.5, 62. , 62.5, 63. , 63.5, 64. , 64.5, 65. , 65.5, 66. , 66.5,
       67. , 67.5, 68. , 68.5, 69. , 69.5, 70. , 70.5, 71. , 71.5, 72. ,
       72.5, 73. , 73.5, 74. , 74.5, 75. , 75.5, 76

In [ ]:
np.linspace(1,100,num=50) # This is used when we want a spcified set of numbers

array([  1.        ,   3.02040816,   5.04081633,   7.06122449,
         9.08163265,  11.10204082,  13.12244898,  15.14285714,
        17.16326531,  19.18367347,  21.20408163,  23.2244898 ,
        25.24489796,  27.26530612,  29.28571429,  31.30612245,
        33.32653061,  35.34693878,  37.36734694,  39.3877551 ,
        41.40816327,  43.42857143,  45.44897959,  47.46938776,
        49.48979592,  51.51020408,  53.53061224,  55.55102041,
        57.57142857,  59.59183673,  61.6122449 ,  63.63265306,
        65.65306122,  67.67346939,  69.69387755,  71.71428571,
        73.73469388,  75.75510204,  77.7755102 ,  79.79591837,
        81.81632653,  83.83673469,  85.85714286,  87.87755102,
        89.89795918,  91.91836735,  93.93877551,  95.95918367,
        97.97959184, 100.        ])

In [ ]:
np.random.randint(low = 1, high = 100, size = 500) # Random draw of numbers

array([ 5, 29, 96,  4, 39,  2, 10, 66, 95, 30, 67, 70, 34, 19, 48, 32, 69,
       38, 84, 94, 37, 71, 22, 11, 48, 74, 70, 77, 88, 19, 24, 73, 32, 13,
       68,  9, 73, 10, 30, 95, 29, 48, 59, 41, 18,  3, 79, 41, 95, 71, 44,
       42, 33, 77, 67, 47, 89, 27,  7,  5, 73, 65,  4, 97, 15, 70, 65, 88,
       66, 72, 17, 57, 43, 11, 13, 40, 82, 51, 64, 22,  4,  8,  9, 65, 64,
       73,  8, 57, 45, 75, 83,  7, 28, 59, 68, 65, 86, 24, 96, 26, 29, 15,
       79, 73,  5, 70, 99, 62, 79, 44, 17, 39, 30, 90, 45, 71, 85, 13, 12,
       72, 34, 44, 18, 61, 29, 11, 86, 45, 34,  1,  9, 91, 11, 69, 24, 95,
       64, 18, 22, 81, 66, 77, 60, 82, 95, 48, 95, 44, 69, 51, 17, 60, 99,
       97, 10, 44,  3, 91, 65, 18, 33, 48,  8, 20,  5, 30, 55, 15, 68, 99,
       42, 37, 83, 18, 36, 29, 15, 29, 58, 32, 48, 71, 40,  7, 18, 37, 41,
       69, 28,  5, 94, 57, 72, 55,  5, 30, 93, 27, 65, 66, 83, 18,  9, 46,
       93, 60, 76, 95, 48, 52, 13, 38, 16, 50, 51, 94, 97, 58, 72, 26, 41,
       46, 88, 12, 64, 55

In [ ]:
a2 = np.linspace(1,50,100)

a2.size

100

In [56]:
a2.reshape((2,5,10))

array([[[ 1.        ,  1.49494949,  1.98989899,  2.48484848,
          2.97979798,  3.47474747,  3.96969697,  4.46464646,
          4.95959596,  5.45454545],
        [ 5.94949495,  6.44444444,  6.93939394,  7.43434343,
          7.92929293,  8.42424242,  8.91919192,  9.41414141,
          9.90909091, 10.4040404 ],
        [10.8989899 , 11.39393939, 11.88888889, 12.38383838,
         12.87878788, 13.37373737, 13.86868687, 14.36363636,
         14.85858586, 15.35353535],
        [15.84848485, 16.34343434, 16.83838384, 17.33333333,
         17.82828283, 18.32323232, 18.81818182, 19.31313131,
         19.80808081, 20.3030303 ],
        [20.7979798 , 21.29292929, 21.78787879, 22.28282828,
         22.77777778, 23.27272727, 23.76767677, 24.26262626,
         24.75757576, 25.25252525]],

       [[25.74747475, 26.24242424, 26.73737374, 27.23232323,
         27.72727273, 28.22222222, 28.71717172, 29.21212121,
         29.70707071, 30.2020202 ],
        [30.6969697 , 31.19191919, 31.68686869, 32

In [ ]:
a2.reshape((50,2)).T # Tanspose could be useful when we are analyzing the info in a cross table

array([[ 1.        ,  1.98989899,  2.97979798,  3.96969697,  4.95959596,
         5.94949495,  6.93939394,  7.92929293,  8.91919192,  9.90909091,
        10.8989899 , 11.88888889, 12.87878788, 13.86868687, 14.85858586,
        15.84848485, 16.83838384, 17.82828283, 18.81818182, 19.80808081,
        20.7979798 , 21.78787879, 22.77777778, 23.76767677, 24.75757576,
        25.74747475, 26.73737374, 27.72727273, 28.71717172, 29.70707071,
        30.6969697 , 31.68686869, 32.67676768, 33.66666667, 34.65656566,
        35.64646465, 36.63636364, 37.62626263, 38.61616162, 39.60606061,
        40.5959596 , 41.58585859, 42.57575758, 43.56565657, 44.55555556,
        45.54545455, 46.53535354, 47.52525253, 48.51515152, 49.50505051],
       [ 1.49494949,  2.48484848,  3.47474747,  4.46464646,  5.45454545,
         6.44444444,  7.43434343,  8.42424242,  9.41414141, 10.4040404 ,
        11.39393939, 12.38383838, 13.37373737, 14.36363636, 15.35353535,
        16.34343434, 17.33333333, 18.32323232, 19.

In [59]:
np.reshape(a2, shape=(50,2))

array([[ 1.        ,  1.49494949],
       [ 1.98989899,  2.48484848],
       [ 2.97979798,  3.47474747],
       [ 3.96969697,  4.46464646],
       [ 4.95959596,  5.45454545],
       [ 5.94949495,  6.44444444],
       [ 6.93939394,  7.43434343],
       [ 7.92929293,  8.42424242],
       [ 8.91919192,  9.41414141],
       [ 9.90909091, 10.4040404 ],
       [10.8989899 , 11.39393939],
       [11.88888889, 12.38383838],
       [12.87878788, 13.37373737],
       [13.86868687, 14.36363636],
       [14.85858586, 15.35353535],
       [15.84848485, 16.34343434],
       [16.83838384, 17.33333333],
       [17.82828283, 18.32323232],
       [18.81818182, 19.31313131],
       [19.80808081, 20.3030303 ],
       [20.7979798 , 21.29292929],
       [21.78787879, 22.28282828],
       [22.77777778, 23.27272727],
       [23.76767677, 24.26262626],
       [24.75757576, 25.25252525],
       [25.74747475, 26.24242424],
       [26.73737374, 27.23232323],
       [27.72727273, 28.22222222],
       [28.71717172,

In [62]:
np.transpose(a2.reshape(50,2))

array([[ 1.        ,  1.98989899,  2.97979798,  3.96969697,  4.95959596,
         5.94949495,  6.93939394,  7.92929293,  8.91919192,  9.90909091,
        10.8989899 , 11.88888889, 12.87878788, 13.86868687, 14.85858586,
        15.84848485, 16.83838384, 17.82828283, 18.81818182, 19.80808081,
        20.7979798 , 21.78787879, 22.77777778, 23.76767677, 24.75757576,
        25.74747475, 26.73737374, 27.72727273, 28.71717172, 29.70707071,
        30.6969697 , 31.68686869, 32.67676768, 33.66666667, 34.65656566,
        35.64646465, 36.63636364, 37.62626263, 38.61616162, 39.60606061,
        40.5959596 , 41.58585859, 42.57575758, 43.56565657, 44.55555556,
        45.54545455, 46.53535354, 47.52525253, 48.51515152, 49.50505051],
       [ 1.49494949,  2.48484848,  3.47474747,  4.46464646,  5.45454545,
         6.44444444,  7.43434343,  8.42424242,  9.41414141, 10.4040404 ,
        11.39393939, 12.38383838, 13.37373737, 14.36363636, 15.35353535,
        16.34343434, 17.33333333, 18.32323232, 19.

In [94]:
# Slicing or dicing of numpy array

a2 = np.arange(1,31).reshape((5,6))

In [70]:
a2

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [ ]:
a2[1:3, 2:3] # fetching rows at 1st and 2nd position along with 2nd column.

array([[ 9],
       [15]])

In [ ]:
a2[::2, ::2] #start=0:stop=end-1:step=1

array([[ 1,  3,  5],
       [13, 15, 17],
       [25, 27, 29]])

In [78]:
a2[2:, 1:4]

array([[14, 15, 16],
       [20, 21, 22],
       [26, 27, 28]])

In [82]:
a2[1:3, 4:]

array([[11, 12],
       [17, 18]])

In [83]:
a2[1:4, 1::2]

array([[ 8, 10, 12],
       [14, 16, 18],
       [20, 22, 24]])

In [86]:
a2[1:2, 1:2] = 100
a2

array([[  1,   2,   3,   4,   5,   6],
       [  7, 100,   9,  10,  11,  12],
       [ 13,  14,  15,  16,  17,  18],
       [ 19,  20,  21,  22,  23,  24],
       [ 25,  26,  27,  28,  29,  30]])

In [95]:
a2[1:4, 1::2] = 100 # Broadcasting
a2

array([[  1,   2,   3,   4,   5,   6],
       [  7, 100,   9, 100,  11, 100],
       [ 13, 100,  15, 100,  17, 100],
       [ 19, 100,  21, 100,  23, 100],
       [ 25,  26,  27,  28,  29,  30]])

In [99]:
temp_a = a2[1:4, 1::2] / 50 # Broadcasting
temp_a

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [103]:
temp_a = temp_a + 1 # Broadcasting
temp_a

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]])

In [104]:
temp_a + np.ones((3,3)) # Vectorization

array([[4., 4., 4.],
       [4., 4., 4.],
       [4., 4., 4.]])

In [105]:
a2[1:4, 1::2] = temp_a # Vectorization
a2

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  3,  9,  3, 11,  3],
       [13,  3, 15,  3, 17,  3],
       [19,  3, 21,  3, 23,  3],
       [25, 26, 27, 28, 29, 30]])

In [108]:
# Filtering of data
# Find values > 5 in a2
a2[a2 > 5]

array([ 6,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 26, 27, 28, 29, 30])

In [109]:
# Find even values in a2

a2[a2%2 == 0]

array([ 2,  4,  6, 26, 28, 30])

In [110]:
# Find even values that are greater than 5
a2[a2%2 == 0]

array([ 2,  4,  6, 26, 28, 30])

In [111]:
a2[a2 > 5]

array([ 6,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 26, 27, 28, 29, 30])

In [ ]:
# Bitwise and - &
# Bitwise or |
# Bitwise not ~
# Bitwise exor ^
a2[(a2 % 2 == 0) & (a2 > 5)] # Bitwise and operator

array([ 6, 26, 28, 30])

In [ ]:
# Fetch the numbers that are completely divisible by 3 or 5.



ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [115]:
a2[(a2%3==0) | (a2%5==0)]

array([ 3,  5,  6,  3,  9,  3,  3,  3, 15,  3,  3,  3, 21,  3,  3, 25, 27,
       30])