# WELCOME TO THE COURSE

## Who am I?
Ellen Visscher
- Third year of DPhil (PhD) at Oxford in statistical machine learning applied to omics
- Worked as software developer using python
- Use python everyday for data-science
- Do a lot of deep learning at the moment
- I am essentially a TA for this course, Nick- who you will see in some of the lectures, has devised the course.


## How will the course work?
- Lectures released in the week prior to the live demos
- Expected to watch these in your own time
- Ideally try the exercises before the live demos
- Will go through the exerises with you in the demos, and emphasize any core concepts

- Lectures are legacy from previous runs of the course. We are constantly updating to improve, but it does mean some content is outdated.
    - We will not be working in gitlab
    - Any adminny things mentioned in those lectures can be ignored
    - Where there are two sets of lectures, Nick's are the most up to date. Both are included as Massi's old lectures often slightly more detailed.



## Requirements from you?
- 3 x assignments- 2 are due at the same time. 
- Attendance is taken, to get Cats points you cannot miss more than a few sessions, unless you email me explicitly.
- Please participate, ask/answer questions. 


## My ethos:
- This is a python for data science class
- However, I am a strong believer in understanding the fundamentals of the tools you use
- I will try to explain the underlying concepts as much as possible
- Many people can write data science code, what make a good data scientist is not running the code, but understanding the code and the data


## Agenda:

- Introductions/register
- Lecture overview
- Looking at exercises

### A unifying framework

- Most machine learning can be framed in a specific way. 
- Framing novel techniques like this will be helpful for YOUR understanding of what these things do, and help to demistify``ML"
- Will get introduced to many algorithms/techniques but you will realise that they are all very related if you can learn how to frame them like this


So what are the components:

- The underlying model, how you are trying to model the data, your $f(x)$. Often assumes a given structure/probability distribution. Models are parametrised- that is they hope to learn. This is what all ML does, it is finding the best parameters for an assumed model. 
    - In a linear regression, the model is a straight line. We are supposing a straight line underpins the data. 
    - In a neural network, the model is a series of linear transformations and non-linearities. We are supposing that a series of linear transformations and non-linearities can model the data from the input to the output. 

- What is learnt, i.e the parameters of the model.
    - In a linear regression, the parameters are the slope and intercept of the line.
    - In a neural network, the parameters are the weights and biases of the network. 

- How the parameters are learnt. This is through a loss function. The assumed best parameters are those that minimise the loss function. 
    - In linear regression, the loss function is the sum of the squared errors. 
    - In a neural network, the loss function can be many things, it depends what the output is. It could also be sum of squared errors.

- How practically the minima of the loss function (i.e the parameters) are found. E.g an optimisation algorithm.
    - In a linear regression, there is an analytical solution to find the minima of the loss function.
    - In a neural network, we use stochastic gradient descent. (You could use gradient descent with linear regression)
    - Sometimes this is heuristic (i.e not guaranteed to find the minima, use some sort of algorithm to ``do better")

All ML is essentially an optimisation problem, computers ``learn" how to find the best parameters for a given model by minimising a loss function.



### Other Resources:

- 3 blue 1 brown- youtube channel

### A note on train/test split:

- A best test set ideally would be separate from your original data. I.e an unseen dataset.
- Be really careful about choosing a test set from your trianing data. 
    - Data leakage- including dependent data when you have assumed it's independent. E,g many observations on many patients, including different observations in both the training and test set that are from the same patient.
    - If you do a random split, but some of your test data is very similar to your training data, you may get a false sense of how well your model is doing. 
    - These are common problems in ML and leads to lots of misreporting of ``good results".


### The make it go away ethos:

- If you find a result that is too good to be true, it probably is. 
- You should try everything in your power to make it go away, and if you can't, then you can start to believe it.
- So much bad data science occurs because not enough reflection on the ways that the data/modelling could be wrong.

## Matrices Operations and Linear Regression

Suggestion: explore the NumPy library documentation to find the right functions to solve the exercises below

NumPy docs: https://numpy.org/doc/stable/

## Setup

In [1]:
import numpy as np  # This should be all the dependencies you will need


### 1.1 Matrix Element Wise-multiplication

Consider the two following matrices 

$$
A = \begin{pmatrix}
1&0&0\\
0&1&0\\
0&0&1\\
\end{pmatrix}
$$

and

$$
B = \begin{pmatrix}
1&2&3\\
4&5&6\\
7&8&9\\
\end{pmatrix}
$$

Write a Python program that computes the element-wise multiplication of the two matrices, i.e.

$$
C = \begin{pmatrix}
1&0&0\\
0&5&0\\
0&0&9\\
\end{pmatrix}
$$

In [2]:
## write your code here

a = np.array([1, 0, 0, 0, 1, 0, 0, 0, 1]).reshape(3, 3)
a


array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [4]:
b = np.arange(1, 10).reshape(3, 3)
b


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
v1 = 3
v2 = 5

v2*v2

In [5]:
a*b

array([[1, 0, 0],
       [0, 5, 0],
       [0, 0, 9]])

### 1.2 Matrix-Matrix Multiplication

![matrix_multiplication](https://www.mathsisfun.com/algebra/images/matrix-multiply-a.svg)

Consider the following two matrices

$$
A = \begin{pmatrix}
2&1&3\\
1&1&2\\
\end{pmatrix}
$$

and

$$
B = \begin{pmatrix}
1&2\\
5&6\\
7&9\\
\end{pmatrix}
$$

Write a Python program that computes the matrix multiplication of the two matrices, i.e.

$$
C = A \times B = \begin{pmatrix}
28&37\\
20&26\\
\end{pmatrix}
$$
Run the same program for the matrices of Exercise 1.1. Which result do you get?

In [9]:
## write your code here
a = np.array([2, 1, 3, 1, 1, 2]).reshape(2, 3)
b = np.array([1, 2, 5, 6, 7, 9]).reshape(3, 2)

b



array([[1, 2],
       [5, 6],
       [7, 9]])

In [10]:
np.dot(a, b)

array([[28, 37],
       [20, 26]])

In [11]:
np.matmul(a, b)

array([[28, 37],
       [20, 26]])

In [12]:
a@b

array([[28, 37],
       [20, 26]])

### 1.3 Linear Regression

We generate some fake "height" and "weight" data about babies between 0 and 12 months of age.

We  want to create  linear predictor that predicts the weight from the baby age (in month).

In [13]:
# generate some fake "height" and "weight" data about babies between 0 and 12 months of age
babies = range(10)
months = np.arange(12)
data = [(month + np.random.rand(), month*24.7 + 96 + np.random.normal(loc=0, scale=20))
        for month in months
        for baby in babies]
month_data = [element[0] for element in data]
weight_data = [element[1] for element in data]
# Let's put the month_data into the matrix X together with the biases column vector
X_1 = np.array(month_data)    # here we put month_data into a row vector called X_1
X_0 = np.ones([X_1.shape[0], 1]) # this is the biases column vector
X_1 = X_1[:, np.newaxis]    # here we convert X_1 from a row vector to a column vector
X = np.concatenate((X_0, X_1), axis=1) # here we concatenate the biases vector to the month_data vector

# Let's put the weight_data into the output vector y
y = np.array(weight_data)

In [16]:
month = months[2]

np.dot(month, 24.7)

49.4

In [ ]:
X.ndim, y.ndim

In [ ]:
X.shape, y.shape

Our features matrix $X$ as a column of biases (all set to 1) and our column of input features (i.e age).

Our labels verctor $y$ is a row vector with our output labels (weights in some unspecified unit)

In [ ]:
X

In [ ]:
y

Given: 
- the two-dimensional array (i.e. a matrix) $X$, containing a column with biases (all set to 1) and a column containing the ages of children (expressed in months)
- a one dimensional column array $y$ containing the weights of the same children expressed in kilograms
Write a function to compute the best fit  using the Linear Regression model with Ordinary Least Squares Method:
$$
\beta = (X^T X)^{-1}X^T y
$$
where, given a matrix $A$, $A^T$ is the transpose matrix of A, and $A^{-1}$ is the inverse matrix of $A$.


The $X$ and $y$ arrays have precomputed for you in the cell above

In [26]:
# Hint: check the NumPy documentation to find the functions to compute the transpose and the inverse of a matrix
def ols(X, y):
    '''returns parameters based on Ordinary Least Squares.'''
    ...

Once you function has been written, you should be able to run the code below:

In [ ]:
# find parameters
params = ols(X,y)
print('intercept: {} | slope: {}'.format(params[0], params[1]))

You should also be able to visualize the result of the OLS fitting running the code in the cell below:

In [ ]:
## here we draw a graph of the linear estimator
import matplotlib.pyplot as plt
%matplotlib inline

fig, axes = plt.subplots(1, 1, figsize=(9, 6))
axes.scatter(month_data, weight_data)
x_vals = np.array(axes.get_xlim())
y_vals = params[0] + params[1] * x_vals
axes.plot(x_vals, y_vals, 'r--')
plt.title('Linear Regression example')
plt.xlabel('Age (Months)')
plt.ylabel('Weight (?)')